# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setStyleSheet("background-color: #353232")
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_login = QtWidgets.QLineEdit(self.centralwidget)
        self.line_login.setGeometry(QtCore.QRect(151, 171, 150, 25))
        self.line_login.setStyleSheet("background-color: #FFF")
        self.line_login.setText("")
        self.line_login.setDragEnabled(False)
        self.line_login.setPlaceholderText("")
        self.line_login.setObjectName("line_login")
        self.line_password = QtWidgets.QLineEdit(self.centralwidget)
        self.line_password.setGeometry(QtCore.QRect(151, 241, 150, 25))
        self.line_password.setStyleSheet("background-color: #FFF")
        self.line_password.setObjectName("line_password")
        self.btn_entry = QtWidgets.QPushButton(self.centralwidget)
        self.btn_entry.setGeometry(QtCore.QRect(141, 301, 170, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_entry.setFont(font)
        self.btn_entry.setStyleSheet("background-color: white; color: #FF6600")
        self.btn_entry.setObjectName("btn_entry")
        self.lbl_login = QtWidgets.QLabel(self.centralwidget)
        self.lbl_login.setGeometry(QtCore.QRect(156, 141, 141, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_login.setFont(font)
        self.lbl_login.setStyleSheet("color: #FF6600")
        self.lbl_login.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_login.setObjectName("lbl_login")
        self.lbl_password = QtWidgets.QLabel(self.centralwidget)
        self.lbl_password.setGeometry(QtCore.QRect(156, 211, 141, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_password.setFont(font)
        self.lbl_password.setStyleSheet("color: #FF6600")
        self.lbl_password.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_password.setObjectName("lbl_password")
        self.lbl_help = QtWidgets.QLabel(self.centralwidget)
        self.lbl_help.setGeometry(QtCore.QRect(90, 370, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_help.setFont(font)
        self.lbl_help.setStyleSheet("color: #FF6600")
        self.lbl_help.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_help.setObjectName("lbl_help")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(176, 411, 90, 30))
        self.btn_login.setStyleSheet("background-color: white; color: #FF6600")
        self.btn_login.setObjectName("btn_login")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(410, 60, 321, 371))
        self.plainTextEdit.setStyleSheet("border-radius: 20px; background-color: white")
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Регистрация"))
        self.btn_entry.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.lbl_login.setText(_translate("MainWindow", "Введите логин"))
        self.lbl_password.setText(_translate("MainWindow", "Введите пароль"))
        self.lbl_help.setText(_translate("MainWindow", "Есть аккаунт? - Войди"))
        self.btn_login.setText(_translate("MainWindow", "Вход"))
