# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'review.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Info_Form(object):
    def setupUi(self, Info_Form):
        Info_Form.setObjectName("Info_Form")
        Info_Form.resize(1912, 1010)
        Info_Form.setStyleSheet("background-color: #353232")
        self.verticalLayoutWidget = QtWidgets.QWidget(Info_Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(29, 28, 1851, 961))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_name = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lbl_name.setFont(font)
        self.lbl_name.setStyleSheet("color: #FF6600")
        self.lbl_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout.addWidget(self.lbl_name)
        self.text_data = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.text_data.setFont(font)
        self.text_data.setStyleSheet("color: white; font-size: 15pt")
        self.text_data.setReadOnly(True)
        self.text_data.setPlainText("")
        self.text_data.setObjectName("text_data")
        self.verticalLayout.addWidget(self.text_data)

        self.retranslateUi(Info_Form)
        QtCore.QMetaObject.connectSlotsByName(Info_Form)

    def retranslateUi(self, Info_Form):
        _translate = QtCore.QCoreApplication.translate
        Info_Form.setWindowTitle(_translate("Info_Form", "Review"))
        self.lbl_name.setText(_translate("Info_Form", "TextLabel"))
